name: Feature Tests
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - feature/**
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - "main"

jobs:
  rapido_feature:
    name: "Rapido Feature Tests"
    uses: RupertBarrow/actions/.github/workflows/cci-standard-workflow-run-flow-scratch.yml@main
    secrets:
      dev-hub-auth-url: "${{ secrets.SFDX_AUTH_URL_RAPIDOCLOUD_DEVHUB }}"
      cumulusci-service-github: "${{ secrets.CUMULUSCI_SERVICE_GITHUB }}"
    with:
      flow-name: "rapido_feature"
      org-name: "feature"

  analyze:
    name: "Static Analysis"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SFDX CLI and Scanner
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run plugins:install @salesforce/sfdx-scanner
      - name: Run SFDX Scanner - Report findings as comments
        uses: mitchspano/sfdx-scan-pull-request@v0.1.5
        with:
          pmdconfig: ruleset.xml
          severity-threshold: 4
          strictly-enforced-rules: '[{ "engine": "pmd", "category": "Performance", "rule": "AvoidDebugStatements" }]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

